/******************************************************************************/
/****        Generated by IBExpert 2024.1.22.1 23/06/2024 17:57:58         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_3_0\WOW64\fbclient.dll';

CREATE DATABASE 'localhost/3050:C:\Dados\BANCO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN "CHAR(1)" AS
CHAR(1);

CREATE DOMAIN "DATE" AS
DATE;

CREATE DOMAIN "DECIMAL(15,2)" AS
DECIMAL(15,2);

CREATE DOMAIN INTERGER AS
INTEGER;

CREATE DOMAIN "VARCHAR(100)" AS
VARCHAR(100);



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ABASTECIMENTOS_ID START WITH 6 INCREMENT BY 1;
SET GENERATOR GEN_ABASTECIMENTOS_ID TO 6;

CREATE GENERATOR GEN_BOMBAS_ID START WITH 5 INCREMENT BY 1;
SET GENERATOR GEN_BOMBAS_ID TO 5;

CREATE GENERATOR GEN_TANQUES_ID START WITH 3 INCREMENT BY 1;
SET GENERATOR GEN_TANQUES_ID TO 3;



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE RESET_GENERATORS
AS
BEGIN
  EXIT;
END^






SET TERM ; ^



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ABASTECIMENTOS (
    ID                  INTERGER NOT NULL,
    DATA                "DATE" NOT NULL,
    ID_BOMBA            INTERGER NOT NULL,
    QUANTIDADE_LITROS   INTERGER NOT NULL,
    VALOR_ABASTECIDO    "DECIMAL(15,2)" NOT NULL,
    VALOR_IMPOSTO       "DECIMAL(15,2)" NOT NULL,
    PERCENTUAL_IMPOSTO  "DECIMAL(15,2)" NOT NULL
);

CREATE TABLE BOMBAS (
    ID         INTERGER NOT NULL,
    DESCRICAO  "VARCHAR(100)" NOT NULL,
    ID_TANQUE  INTERGER NOT NULL
);

CREATE TABLE TANQUES (
    ID               INTERGER NOT NULL,
    DESCRICAO        "VARCHAR(100)" NOT NULL,
    TIPOCOMBUSTIVEL  "CHAR(1)" NOT NULL
);

INSERT INTO TANQUES (ID, DESCRICAO, TIPOCOMBUSTIVEL) VALUES (1, 'GASOLINA', 'G');
INSERT INTO TANQUES (ID, DESCRICAO, TIPOCOMBUSTIVEL) VALUES (2, 'ÓLEO DIESEL', 'O');


COMMIT WORK;

INSERT INTO BOMBAS (ID, DESCRICAO, ID_TANQUE) VALUES (1, 'BOMBA 01', 1);
INSERT INTO BOMBAS (ID, DESCRICAO, ID_TANQUE) VALUES (2, 'BOMBA 02', 1);
INSERT INTO BOMBAS (ID, DESCRICAO, ID_TANQUE) VALUES (3, 'BOMBA 03', 2);
INSERT INTO BOMBAS (ID, DESCRICAO, ID_TANQUE) VALUES (4, 'BOMBA 04', 2);


COMMIT WORK;

INSERT INTO ABASTECIMENTOS (ID, DATA, ID_BOMBA, QUANTIDADE_LITROS, VALOR_ABASTECIDO, VALOR_IMPOSTO, PERCENTUAL_IMPOSTO) VALUES (1, '2024-06-19', 2, 20, 40, 5.2, 13);
INSERT INTO ABASTECIMENTOS (ID, DATA, ID_BOMBA, QUANTIDADE_LITROS, VALOR_ABASTECIDO, VALOR_IMPOSTO, PERCENTUAL_IMPOSTO) VALUES (2, '2024-06-21', 1, 15, 50, 6.5, 13);
INSERT INTO ABASTECIMENTOS (ID, DATA, ID_BOMBA, QUANTIDADE_LITROS, VALOR_ABASTECIDO, VALOR_IMPOSTO, PERCENTUAL_IMPOSTO) VALUES (3, '2024-06-18', 2, 10, 60, 7.8, 13);
INSERT INTO ABASTECIMENTOS (ID, DATA, ID_BOMBA, QUANTIDADE_LITROS, VALOR_ABASTECIDO, VALOR_IMPOSTO, PERCENTUAL_IMPOSTO) VALUES (4, '2024-06-21', 3, 10, 60, 7.8, 13);
INSERT INTO ABASTECIMENTOS (ID, DATA, ID_BOMBA, QUANTIDADE_LITROS, VALOR_ABASTECIDO, VALOR_IMPOSTO, PERCENTUAL_IMPOSTO) VALUES (5, '2024-06-21', 1, 10, 1, 0.13, 13);


COMMIT WORK;



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTOS ADD CONSTRAINT PK_ABASTECIMENTOS PRIMARY KEY (ID);
ALTER TABLE BOMBAS ADD CONSTRAINT PK_BOMBAS PRIMARY KEY (ID);
ALTER TABLE TANQUES ADD CONSTRAINT PK_TANQUES PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTOS ADD CONSTRAINT FK_ABASTECIMENTOS_1 FOREIGN KEY (ID_BOMBA) REFERENCES BOMBAS (ID);
ALTER TABLE BOMBAS ADD CONSTRAINT FK_BOMBAS_1 FOREIGN KEY (ID_TANQUE) REFERENCES TANQUES (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: ABASTECIMENTOS_BI */
CREATE TRIGGER ABASTECIMENTOS_BI FOR ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_abastecimentos_id,1);
end
^

/* Trigger: BOMBAS_BI */
CREATE TRIGGER BOMBAS_BI FOR BOMBAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_bombas_id,1);
end
^

/* Trigger: TANQUES_BI */
CREATE TRIGGER TANQUES_BI FOR TANQUES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_tanques_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE RESET_GENERATORS
AS
declare variable v_max_id integer;
begin
  execute statement 'select coalesce(max(id) + 1, 1) from abastecimentos' into :v_max_id;
  execute statement 'alter sequence gen_abastecimentos_id restart with ' || :v_max_id;

  execute statement 'select coalesce(max(id) + 1, 1) from bombas' into :v_max_id;
  execute statement 'alter sequence gen_bombas_id restart with ' || :v_max_id;

  execute statement 'select coalesce(max(id) + 1, 1) from tanques' into :v_max_id;
  execute statement 'alter sequence gen_tanques_id restart with ' || :v_max_id;
end^



SET TERM ; ^



/******************************************************************************/
/****                         Fields descriptions                          ****/
/******************************************************************************/

COMMENT ON COLUMN TANQUES.TIPOCOMBUSTIVEL IS
'G - GASOLINA
O - ÓLEO DIESEL';

